openapi: 3.0.0
info:
  title: Event and Heritage Management API
  description: API documentation for managing accounts, login logs, favorites, festivals, and heritage data.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Local development server

paths:
  /accounts:
    get:
      summary: Get all accounts
      responses:
        "200":
          description: List of accounts
    post:
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        "201":
          description: Account created
    put:
      summary: Update account permissions
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Permissions"
      responses:
        "200":
          description: Permissions updated
    delete:
      summary: Delete an account
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Account deleted

  /login-log:
    get:
      summary: Get all login logs
      responses:
        "200":
          description: List of login logs
    post:
      summary: Add a login log entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginLog"
      responses:
        "201":
          description: Login log created

  /favoritelist:
    get:
      summary: Get all favorite items
      responses:
        "200":
          description: List of favorite items
    post:
      summary: Add a favorite item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Favorite"
      responses:
        "201":
          description: Favorite added
    delete:
      summary: Remove a favorite item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Favorite"
      responses:
        "200":
          description: Favorite removed

  /heritagelist:
    get:
      summary: Get heritage list
      responses:
        "200":
          description: List of heritage items

  /festivallist:
    get:
      summary: Get festival list
      responses:
        "200":
          description: List of festival items

components:
  schemas:
    Account:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        email:
          type: string
        username:
          type: string
        password:
          type: string
        created_at:
          type: string
          format: date-time
        is_admin:
          type: boolean

    LoginLog:
      type: object
      properties:
        admin_uuid:
          type: string
          format: uuid
        client_uuid:
          type: string
          format: uuid
        action:
          type: string
        timestamp:
          type: string
          format: date-time

    Favorite:
      type: object
      properties:
        token:
          type: string
        f_id:
          type: integer
        h_id:
          type: integer
        type:
          type: string

    Permissions:
      type: object
      properties:
        is_admin:
          type: boolean
