openapi: 3.0.0
info:
  title: Event and Heritage Management API
  description: API documentation for managing accounts, events, festivals, and favorites.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local development server

paths:
  /accounts:
    get:
      summary: Get all accounts
      responses:
        "200":
          description: List of accounts
    post:
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        "201":
          description: Account created
    put:
      summary: Update account permissions
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Permissions"
      responses:
        "200":
          description: Permissions updated
    delete:
      summary: Delete an account
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Account deleted

  /login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        "200":
          description: Login successful

  /logout:
    post:
      summary: Log out a user
      responses:
        "200":
          description: Logout successful

  /favoritelist:
    get:
      summary: Get favorite items
      responses:
        "200":
          description: List of favorite items
    post:
      summary: Add a favorite item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Favorite"
      responses:
        "201":
          description: Favorite added
    delete:
      summary: Remove a favorite item
      responses:
        "200":
          description: Favorite removed

  /heritage:
    get:
      summary: Get heritage information
      responses:
        "200":
          description: Heritage data

  /festivals:
    get:
      summary: Get festival information
      responses:
        "200":
          description: Festival data

components:
  schemas:
    Account:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        email:
          type: string
        username:
          type: string
        password:
          type: string
        created_at:
          type: string
          format: date-time
        is_admin:
          type: boolean

    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    Permissions:
      type: object
      properties:
        is_admin:
          type: boolean

    Favorite:
      type: object
      properties:
        token:
          type: string
        f_id:
          type: integer
        h_id:
          type: integer
        type:
          type: string
