swagger: "2.0"
info:
  title: Cultural Heritage API
  description: API for cultural heritage information and user management
  version: "1.0.0"

host: localhost:4000
basePath: /api
schemes:
  - http

paths:
  /account/register:
    post:
      tags:
        - Account
      summary: Register new user
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
      responses:
        200:
          description: Successfully registered
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Registration successful"
        400:
          description: Registration failed

  /account/login:
    post:
      tags:
        - Account
      summary: User login
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Login successful
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                type: object
                properties:
                  email:
                    type: string
                  name:
                    type: string
        401:
          description: Invalid credentials

  /account/user-info:
    get:
      tags:
        - Account
      summary: Get user information
      security:
        - Bearer: []
      responses:
        200:
          description: User information retrieved successfully
          schema:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
        401:
          description: Unauthorized

  /events:
    get:
      tags:
        - Events
      summary: Get cultural events
      responses:
        200:
          description: List of cultural events
          schema:
            type: array
            items:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
                location:
                  type: string
                contact:
                  type: string
                region:
                  type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    type: object
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string

  Event:
    type: object
    properties:
      title:
        type: string
      description:
        type: string
      startDate:
        type: string
      endDate:
        type: string
      location:
        type: string
      contact:
        type: string
      region:
        type: string
